'''
Given a string s consisting only of letters 'a' and 'b'. In a single step you can remove one palindromic subsequence from s.

Return the minimum number of steps to make the given string empty.

A string is a subsequence of a given string, if it is generated by deleting some characters of a given string without changing its order.

A string is called palindrome if is one that reads the same backward as well as forward.

 

Example 1:

Input: s = "ababa"
Output: 1
Explanation: String is already palindrome

'''
def removePalindromeSub(s):
    if(len(s)==0):
        return 0
    if(s==s[::-1]):
        return 1
    else:
        return 2

s = "ababa"
print(removePalindromeSub(s))